apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: win11-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: win11-vm
    spec:
      domain:
        cpu:
          cores: 4
        resources:
          requests:
            memory: 8Gi
        machine:
          type: q35
        devices:
          disks:
            - name: windows-iso
              cdrom:
                bus: sata
            - name: windows-disk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: windows-iso
          hostDisk:
            path: /home/ubuntu/boot.iso
            type: Disk
        - name: windows-disk
          hostDisk:
            path: /home/ubuntu/vm.qcow2
            type: Disk
      terminationGracePeriodSeconds: 0

---
apiVersion: v1
kind: Service
metadata:
  name: win11-vnc
spec:
  type: NodePort
  selector:
    kubevirt.io/domain: win11-vm
  ports:
    - name: vnc
      port: 5900
      targetPort: 5900

---

# ===============================
# Guacamole Deployment
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      volumes:
        - name: guac-config
          configMap:
            name: guacamole-config
      containers:
        - name: guacamole
          image: guacamole/guacamole
          env:
            - name: GUACD_HOSTNAME
              value: localhost
            - name: GUACD_PORT
              value: "4822"
            - name: GUACAMOLE_HOME
              value: /etc/guacamole
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: guac-config
              mountPath: /etc/guacamole
        - name: guacd
          image: guacamole/guacd
          ports:
            - containerPort: 4822

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
data:
  user-mapping.xml: |
    <user-mapping>
      <authorize username="guacadmin" password="guacadmin-NARF">
        <connection name="Windows 11 RDP">
          <protocol>rdp</protocol>
          <param name="hostname">win11-vm</param>
          <param name="port">3389</param>
        </connection>
        <connection name="Windows 11 VNC">
          <protocol>vnc</protocol>
          <param name="hostname">win11-vnc</param>
          <param name="port">5900</param>
        </connection>
      </authorize>
    </user-mapping>

---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-web
spec:
  type: NodePort
  selector:
    app: guacamole
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: win11
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-http01
spec:
  rules:
  - host: w11.ozan.jmcateer.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guacamole-web
            port:
              number: 8080
  tls:
  - hosts:
      - w11.ozan.jmcateer.com
    secretName: win11-tls
