# ===============================
# Root Disk for Windows 11
# ===============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win11-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  storageClassName: local-path

---
# ===============================
# HostPath PV for ISO
# ===============================
apiVersion: v1
kind: PersistentVolume
metadata:
  name: win11-iso-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /home/ubuntu/win11.iso
    type: File

---
# ===============================
# PVC for ISO
# ===============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: win11-iso
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
  volumeName: win11-iso-pv

---
# ===============================
# Windows 11 VirtualMachine
# ===============================
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: windows11
  annotations:
    kubevirt.io/allow-privileged: "true"
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows11
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: kubernetes.io/hostname
      #               operator: In
      #               values:
      #                 - <NODE_WITH_ISO>  # <-- Replace with your node
      domain:
        firmware:
          bootloader:
            efi:
              secureBoot: true
        features:
          smm:
            enabled: true
        cpu:
          cores: 4
        resources:
          requests:
            memory: 8Gi
        devices:
          tpm:
            enabled: true
          disks:
            - name: rootdisk
              disk:
                bus: virtio
            - name: win11-iso
              cdrom:
                bus: sata
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: win11-pvc
        - name: win11-iso
          persistentVolumeClaim:
            claimName: win11-iso

---
# ===============================
# RDP Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: win11-rdp
spec:
  selector:
    kubevirt.io/domain: windows11
  ports:
    - name: rdp
      port: 3389
      targetPort: 3389

---
# ===============================
# Guacamole Deployment
# ===============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      volumes:
        - name: guac-config
          configMap:
            name: guacamole-config
      containers:
        - name: guacamole
          image: guacamole/guacamole
          env:
            - name: GUACD_HOSTNAME
              value: localhost
            - name: GUACD_PORT
              value: "4822"
            - name: GUACAMOLE_HOME
              value: /etc/guacamole
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: guac-config
              mountPath: /etc/guacamole
        - name: guacd
          image: guacamole/guacd
          ports:
            - containerPort: 4822

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-config
data:
  user-mapping.xml: |
    <user-mapping>
      <authorize username="guacadmin" password="guacadmin-NARF">
        <connection name="Example">
          <protocol>rdp</protocol>
          <param name="hostname">win11-rdp</param>
          <param name="port">3389</param>
        </connection>
      </authorize>
    </user-mapping>
---
# ===============================
# Guacamole Web Access Service
# ===============================
apiVersion: v1
kind: Service
metadata:
  name: guacamole-web
spec:
  type: NodePort
  selector:
    app: guacamole
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30888
---
# ===============================
# Guacamole Ingress controller for w11.ozan.jmcateer.com
# ===============================
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: win11
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-http01
    # traefik.ingress.kubernetes.io/router.entrypoints: websecure
    # traefik.ingress.kubernetes.io/router.middlewares: win11-auth@kubernetescrd
spec:
  rules:
  - host: w11.ozan.jmcateer.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: guacamole-web
            port:
              number: 8080
  tls:
  - hosts:
      - w11.ozan.jmcateer.com
    secretName: win11-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: win11-auth
spec:
  basicAuth:
    secret: win11-basic-auth
---
